### ISSUE TITLE
Implement configuration path parsing

### ISSUE THREAD

**Issue by vix597** [ameily/cincoconfig#15]
It seems like it would be useful if there was a top-level helper method (maybe called `get_path`) in `Field` that would return the full path to that field. I imagine the definition being something like this:

```python
class Field:
    def get_path(self, sep="."):
        pass
```

Additionally, we will need to add support in the `BaseSchema` to index by path. I would expect the usage and output to look like this:

## Usage

```python
schema = Schema()
schema.mode = ApplicationModeField(default='production')
schema.http.port = PortField(default=8080, required=True)
schema.http.ssl.enabled = BoolField(default=False)
schema.some.really.nested.config.value.that.I.would.rather.not.have.to.type.all.the.time = BoolField(default=False)

mode_p = schema.mode.get_path()
port_p = schema.http.port.get_path()
ssl_p = schema.http.ssl.enabled.get_path(sep="/")
long_p = schema.some.really.nested.config.value.that.I.would.rather.not.have.to.type.all.the.time.get_path()

print(mode_p)
print(port_p)
print(ssl_p)
print(long_p)

print()

print(schema[mode_p])
print(schema[port_p])
print(schema[ssl_p])
print(schema[long_p])

print()

config = schema()

print(config[mode_p])
print(config[port_p])
print(config[ssl_p])
print(config[long_p])
```

## Output

```
mode
http.port
http/ssl/enabled
some.really.nested.config.value.that.I.would.rather.not.have.to.type.all.the.time

ApplicationModeField@sfhksdhfd
PortField@sfhksdjf
BoolField@slfhkjdsf
BoolField@shfkjdsf

production
8080
False
False
```

_NOTE: Per the output example above, both `get_path` and the path indexing should work a `BaseSchema` object and a `BaseConfig`._

**Comment by ameily** [comment]
After discussing this with @vix597, the path forward is two fold:

1. Change the field storage from `dict` to `OrderedDict` so that the order in which fields were added to the schema is preserved when iterating over the fields.
1. Add a `Schema.get_all_fields()` method that recursively returns the list of all fields and schemas. The return value will be a list of tuples: `(path, schema, field)`, where `path` is the full path to the field, `schema` is the schema that the field belongs to, and `field` is the field/schema instance.

```python
>>> schema = Schema()
>>> schema.x = IntField()
>>> schema.y = StringField()
>>> schema.z.a = StringField()
>>> schema.get_all_fields()
[
    ('x', schema, schema.x),
    ('y', schema, schema.y),
    ('z', schema, schema.z),
    ('z.a', schema.z, schema.z.a)
]
```

**Comment by ameily** [comment]
@vix597 This has been merged into master and I put up a new release, v0.4.0
