### ISSUE TITLE
FilenameField should only check file exists if value is non-NULL or if required is True

### ISSUE THREAD

**Issue by vix597** [ameily/cincoconfig#19]
If you do something like this:

```
ssl_ca_certs = FilenameField(exists="file", required=False)
```

and the value in the config is `null` - You get a `ValueError` - I would expect that since I'm saying it's not required (meaning the value can be `null`) that this wouldn't raise an exception.

**Comment by ameily** [comment]
I would be surprised that this is being called because in `abc.Field.validate()`, we don't call `_validate()` if the value is None: https://github.com/ameily/cincoconfig/blob/master/cincoconfig/abc.py#L129
