### ISSUE TITLE
"Encrypted" or Secure FIeld

### ISSUE THREAD

**Issue by ameily** [ameily/cincoconfig#2]
It'd be nice to be able to securely store sensitive config values within a config file. It doesn't have to be perfect, it'd just be nice to have a protection in place to stop from someone viewing credentials in plain text.

One way we can do this is copy how Django does it with a `SECRET_KEY`. Where the application has a secret key hardcoded. The secret key would be application-specific.

With our goal of limiting dependencies, we'd have to stick with the standard library.

We would also need a script to generate secure values. Or somehow flag a value as secure. In a perfect world, parsing a config file like this:

```json
{
  "mongodb": {
    "creds": "user:password"
  }
}
```

The parser would read the `creds` string value, transparently encrypt it, and write it back to the config:

```json
{
  "mongodb": {
    "creds": {
        "type": "secure_value",
        "value": "<salt>:<encrypted value>"
    }
  }
}
```

So this issue contains two parts:

1. a method to encrypt or securely store a string value with the Python stdlib
2. a new `Field` that can read both string and secure values and automatically secure string values. This can be done in the API right now by implemented `Field.to_python`.

**Comment by vix597** [comment]
I ended up doing a little extra (hopefully not overboard). I created `SecureStringField` which will handle hashing or encrypting. There are still some TODOs in there. Right now encryption is AES 256 using pycrypto  (which is optional). The dependency-free solution will be XOR. I still need to generate and use a key file for when it's in crypto mode. For that I'll be doing it like the django `SECRET_KEY` approach.

Let me know what you think. The motivation behind supporting hashes was to support things things like a shadow file or some use-case where all the user's and hashed passwords are stored in a config file.

**Comment by vix597** [comment]
Also, I had to override most of the builtin methods like __setval__, __getval__, __setdefault__, etc... because I needed to transparently encrypt/decrypt things as the config field is used and I had to handle hashing. 

The trickiest part was getting it so that I wasn't hash things more than once (which is why I ended up adding the `self.hashed` bool to the class).
