### ISSUE TITLE
Entering an invalid choice for application mode doesn't show the valid choices available

### ISSUE THREAD

**Issue by vix597** [ameily/cincoconfig#23]
Error message for ApplicationMode and really any `StringField` with choices should be updated to include valid choices. This could blow up error output, so I propose either hard-coding a limited number of choices to display or exposing an option in the field to display valid choices on error.

**Comment by ameily** [comment]
I added this by adjusting the error message to include the available choices if there are 5 or fewer choices:

```
value is not a valid choice: must be one of: x, y, z
```
