### ISSUE TITLE
Generate Argparse parser based on config schema

### ISSUE THREAD

**Issue by Rudedog9d** [ameily/cincoconfig#37]
Feature Idea: Add the ability to generate an ArgumentParser object based on a config schema. The application could retrieve this argparse object, parse args, then pass the args into `cmdline_args_override`.

The generated calls to `add_argument` could also add in support for parsing from Environment variables:

```py
parser = argparse.ArgumentParser(description='test')
parser.add_argument('--url', default=os.environ.get('URL'))
```

It would be nice to choose to include/exclude certain fields from being overridden, but I'm not sure what that would look like. It could be another argument to the `Field` class, or a list of config paths to include/exclude (ex, `include=['config.http', 'config.port')`).

**Comment by ameily** [comment]
Are you thinking that it's a script the developer runs to generate a code block they copy/paste into their app, or something that they call at runtime?

```
# Option 1
python -m cincoconfig.genargparse --input config.py --output runme.py

# Option 2
from .config import config
from cincoconfig import generate_argparse

parser = generate_argparse(config, exclude=('http.*', 'db.*'))
parser.add_argument('-v', '--verbose')
args = parser.parse_args()
```

**Comment by Rudedog9d** [comment]
My thought is something that can be called at runtime, exactly like option 2
