### ISSUE TITLE
Field Environment Variable

### ISSUE THREAD

**Issue by ameily** [ameily/cincoconfig#43]
Create a new attribute for the `Field` class, `Field.env`, that specifies the environment variable that overrides the config value. The env variable would override both the `Field.default` and any values loaded from a configuration file. So, if a configuration file sets a field to `X` but the corresponding environment variable is set to `Y`, the config's value would be `Y` (the env variable.)

To make it easier, there will be a helper value that will autogenerate the environment variable based on the `Field.key`:

```python
# these two lines are equivalent
schema.db.host = HostnameField(env='DB_HOST')
schema.db.host = HostnameField(env=True)
```

**Comment by ameily** [comment]
@Rudedog9d Can you verify if this would help you?

**Comment by vix597** [comment]
I don't know about @Rudedog9d but I can think of one place I would use this right away.

**Comment by Rudedog9d** [comment]
@ameily Could there also be an `env: bool = False` on the `Schema()` constructor, that sets whether environment variable generation is active on all the fields and sub-schemas? That way, someone can enable env vars for all fields automatically, or all except a few.

**Comment by ameily** [comment]
> Could there also be an env: bool = False on the Schema() constructor, that sets whether environment variable generation is active on all the fields and sub-schemas?

I love it. If it's a string, it would be a prefix prepended to all env vars.

```python
schema = Schema(env='MYAPP_')
schema.x = Field()  # env = MYAPP_X
schema.y = Field(env=False) # no env var
```

**Comment by Rudedog9d** [comment]
Oh yea, a prefix is a great idea!
