### ISSUE TITLE
Provide a function to get a dictionary of values

### ISSUE THREAD

**Issue by Rudedog9d** [ameily/cincoconfig#50]
Provide a function similiar to `dumps` that returns a dictionary of the data within a schema. A method named `dict()` would make sense and be consistent with [Pydantic](https://pydantic-docs.helpmanual.io/usage/exporting_models/#modeldict).

Currently using `schema.field._data` for this functionality.

**Comment by ameily** [comment]
Are you referring to the config or the schema?

**Comment by Rudedog9d** [comment]
The config, after data has been loaded. It's possible I'm missing something, is that already a feature? I glanced through the docs and didn't find anything.

**Comment by ameily** [comment]
There is `config.to_tree()`, but that calls `Field.to_basic()`, so you may not get the actual data. Adding a `dict()` method would be straightforward

**Comment by ameily** [comment]
@Rudedog9d 

- Do you want a copy of the `_data` or are you looking to modify it?
- Do you want the `dict` to have virtual field values in it?

**Comment by Rudedog9d** [comment]
@ameily I'm looking for a copy of the data, no need to modify. `to_tree()` was encrypting sensitive values, and I need sensitive fields as their plain-text representation. The use case is passing the dictionary as a configuration to another Python application.

**Comment by ameily** [comment]
@Rudedog9d this is in PR #47. There's a new `asdict` method
